### ISSUE TITLE
parseSFML: Add 3rd param - arguments

### ISSUE THREAD

**Issue by 10Dozen** [10Dozen/dzn_commonFunctions#21]
Add 3rd parameter -- parser's scope arguments (type: any), that will be available during parse time as `_this`.

To be used in expressions:
```sqf
private _args = [1, 2, 3];
["test.yml", "PARSE_FILE", _args] call dzn_fnc_parseSFML;
```

```yml
# test.yml
MyVar1: `_this select 0`  # == 1
MyVar2: `_this select 1`  # == 2
```
